import json
import csv
import sys
import os

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>프랜차이즈 업종 분석 (공정거래위원회 공공데이터 2024)</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body { font-family: 'Noto Sans KR', sans-serif; background-color: #f4f4f9; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 40px; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { text-align: center; color: #2c3e50; margin-bottom: 40px; }
        h2 { border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 50px; color: #34495e; }
        .chart-container { position: relative; height: 300px; width: 100%; margin-bottom: 30px; }
        .advice-box { background-color: #e8f6f3; border-left: 5px solid #1abc9c; padding: 20px; margin: 20px 0; border-radius: 5px; }
        .advice-title { font-weight: bold; color: #16a085; margin-bottom: 10px; font-size: 1.1em; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .rank-badge { background-color: #e74c3c; color: white; padding: 3px 8px; border-radius: 12px; font-size: 0.8em; margin-right: 5px; }
        footer { margin-top: 50px; text-align: center; color: #7f8c8d; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>프랜차이즈 업종 분석 리포트</h1>
        <p style="text-align: center;">2024년 정보공개서 데이터를 기반으로 서울 소상공인을 위한 트렌드 분석</p>

        <div class="advice-box">
            <div class="advice-title">💡 서울 소상공인을 위한 핵심 조언</div>
            <ul>
                <li><strong>성장세 주목:</strong> 신규 개점 수가 많은 브랜드는 시장의 수요가 높다는 것을 의미합니다. 특히 배달 및 소자본 창업 아이템이 강세입니다.</li>
                <li><strong>폐점률 체크:</strong> 급성장하는 브랜드 중 일부는 폐점 수도 많을 수 있습니다. 순증가(신규-폐점) 지표를 반드시 확인하세요.</li>
                <li><strong>매출액 분석:</strong> 단순 매출액보다는 매장 면적당 매출액이나 초기 투자비용 대비 수익성을 따져봐야 합니다.</li>
            </ul>
        </div>

        <h2>🔥 뜨는 브랜드 (신규 개점 Top 5)</h2>
        <div class="chart-container">
            <canvas id="growthChart"></canvas>
        </div>
        
        <h2>💰 고수익 브랜드 (평균 매출 Top 5)</h2>
        <div class="chart-container">
            <canvas id="salesChart"></canvas>
        </div>

        <h2>📉 폐점 주의 브랜드 (폐점 수 상위)</h2>
        <div class="chart-container">
            <canvas id="closeChart"></canvas>
        </div>

        <h2>🏆 종합 순위 (성장 순증가 Top 10)</h2>
        <table>
            <thead>
                <tr>
                    <th>순위</th>
                    <th>브랜드명</th>
                    <th>신규개점</th>
                    <th>순증가</th>
                    <th>전체점포</th>
                    <th>평균매출(천원)</th>
                </tr>
            </thead>
            <tbody id="tableBody">
            </tbody>
        </table>

        <footer>
            <p>Data Source: 공정거래위원회 가맹사업거래 정보공개서 (2024)</p>
            <p>Generated by AI Assistant</p>
        </footer>
    </div>

    <script>
        const growthData = __GROWTH_DATA__;
        const salesData = __SALES_DATA__;
        const closeData = __CLOSE_DATA__;
        const tableData = __TABLE_DATA__;

        new Chart(document.getElementById('growthChart'), {
            type: 'bar',
            data: {
                labels: growthData.map(d => d.brand),
                datasets: [{
                    label: '신규 개점 수',
                    data: growthData.map(d => d.new_open),
                    backgroundColor: 'rgba(52, 152, 219, 0.7)',
                    borderColor: 'rgba(52, 152, 219, 1)',
                    borderWidth: 1
                }]
            },
            options: { responsive: true, maintainAspectRatio: false }
        });

        new Chart(document.getElementById('salesChart'), {
            type: 'bar',
            data: {
                labels: salesData.map(d => d.brand),
                datasets: [{
                    label: '평균 매출액 (천원)',
                    data: salesData.map(d => d.avg_sales),
                    backgroundColor: 'rgba(46, 204, 113, 0.7)',
                    borderColor: 'rgba(46, 204, 113, 1)',
                    borderWidth: 1
                }]
            },
            options: { responsive: true, maintainAspectRatio: false }
        });

        new Chart(document.getElementById('closeChart'), {
            type: 'bar',
            data: {
                labels: closeData.map(d => d.brand),
                datasets: [{
                    label: '계약 종료+해지 수',
                    data: closeData.map(d => d.close_count),
                    backgroundColor: 'rgba(231, 76, 60, 0.7)',
                    borderColor: 'rgba(231, 76, 60, 1)',
                    borderWidth: 1
                }]
            },
            options: { responsive: true, maintainAspectRatio: false }
        });

        const tableBody = document.getElementById('tableBody');
        tableData.forEach((row, index) => {
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td><span class="rank-badge">${index + 1}</span></td>
                <td>${row.brand}</td>
                <td>${row.new_open.toLocaleString()}</td>
                 <td style="color: ${row.net_growth > 0 ? 'blue' : 'red'}">${row.net_growth > 0 ? '+' : ''}${row.net_growth.toLocaleString()}</td>
                <td>${row.total_stores.toLocaleString()}</td>
                <td>${row.avg_sales.toLocaleString()}</td>
            `;
            tableBody.appendChild(tr);
        });
    </script>
</body>
</html>
"""

def generate_report(csv_file, output_html):
    data = []
    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                for key in ['total_stores', 'new_open', 'terminate', 'cancel', 'transfer', 'avg_sales', 'area_sales']:
                    row[key] = int(row[key])
            except ValueError:
                continue
            
            suspicious_numbers = range(2019, 2026)
            if row['new_open'] > 20000: continue
            if row['terminate'] + row['cancel'] > 20000: continue
            
            # 엄격한 필터링: 연도 숫자 그대로 들어간 경우 제외 (단, total_stores가 아주 많으면 허용)
            # 예: 락꼬꼬 전체 8개인데 폐점 2018개 -> 명백한 오류.
            is_suspicious_terminate = (row['terminate'] + row['cancel']) in suspicious_numbers
            is_suspicious_new = row['new_open'] in suspicious_numbers
            
            if is_suspicious_terminate and row['total_stores'] < (row['terminate'] + row['cancel']) * 0.5:
                # 전체 점포의 50%보다 폐점수가 많은데 그 수가 연도와 같다면 제외
                continue
            if is_suspicious_new and row['total_stores'] < row['new_open'] * 0.1:
                # 전체 점포의 10% 미만인데 신규가 연도와 같다면? (신규 브랜드일 수 있으니 애매하지만 필터링)
                 continue

            if row['avg_sales'] > 5000000: continue

            row['close_count'] = row['terminate'] + row['cancel']
            row['net_growth'] = row['new_open'] - row['close_count']
            
            data.append(row)

    sorted_by_new = sorted(data, key=lambda x: x['new_open'], reverse=True)[:5]
    sorted_by_sales = sorted(data, key=lambda x: x['avg_sales'], reverse=True)[:5]
    sorted_by_close = sorted(data, key=lambda x: x['close_count'], reverse=True)[:5]
    sorted_by_growth = sorted(data, key=lambda x: x['net_growth'], reverse=True)[:10] 

    html_content = HTML_TEMPLATE.replace('__GROWTH_DATA__', json.dumps(sorted_by_new, ensure_ascii=False))
    html_content = html_content.replace('__SALES_DATA__', json.dumps(sorted_by_sales, ensure_ascii=False))
    html_content = html_content.replace('__CLOSE_DATA__', json.dumps(sorted_by_close, ensure_ascii=False))
    html_content = html_content.replace('__TABLE_DATA__', json.dumps(sorted_by_growth, ensure_ascii=False))

    with open(output_html, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"Report generated: {output_html}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_report.py <csv_file> <output_html>")
        sys.exit(1)
    generate_report(sys.argv[1], sys.argv[2])
